### ISSUE TITLE
npm run clean : windows support

### ISSUE THREAD

**Issue by ofirgeller** [piotrwitek/react-redux-typescript-webpack-starter#1]
This command works: 

`DEL /s /q dist`

Is there anyway to change package.json so the script uses DEL or rm depending on platform?

**Comment by piotrwitek** [comment]
there are already few common solutions to this problem ( e.g. `rimraf` package) which I would prefer rather that implementing own solution

**Comment by nicodeslandes** [comment]
I used the solution suggested by @piotrwitek :
* run `yarn add rimraf --dev`
* change the package.json to replace the "clean" scripts element with `"clean": "rimraf dist"`

This seems to make things work on Windows. The only small annoyance is that an extra Window showing the inner node process output shows up. Haven't been able to track down why yet...

**Comment by ofirgeller** [comment]
Instructions Unclear, rimraf-ed my entire hard drive.

Seriously now, this seems like an improvement to the template with no downsides.
