### ISSUE TITLE
ts-loader could be faster with fork-ts-checker-webpack-plugin / thread-loader / happypack

### ISSUE THREAD

**Issue by johnnyreilly** [piotrwitek/react-redux-typescript-webpack-starter#4]
Hey!

I just stumbled upon this project as I was browsing around for a good redux starter kit.  I noted that you've got ts-loader in here; I don't know if you're aware but you could speed up your ts-loader builds fairly straightforwardly with fork-ts-checker-webpack-plugin / thread-loader / happypack.  I did a blog post about this recently and thought I'd share it.  

https://medium.com/webpack/typescript-webpack-super-pursuit-mode-83cc568dea79

(Feel free to close this; not actually an issue)

**Comment by piotrwitek** [comment]
Hey :)
Thanks for the suggestion and also sharing your great article 👍 

For my development workflow perspective the only concern for me is hot-reload incremental build speed.
Right now it is under 700ms for quite big SPA commercial project I'm currently working on which is not that bad.
Clean boilerplate is about 100ms so there is no big impact from adding hundreds of modules. 
Of course the warming phase (23s) and prod build (37s) slowed down a bit but it's not an issue.

This is what webpack reports about modules count for above mentioned times for reference:
```
   [0] ./~/react/index.js 190 bytes {0} [built]
   [9] ./~/tslib/tslib.es6.js 7.83 kB {0} [built]
  [13] ./~/react-dom/index.js 198 bytes {0} [built]
  [34] ./~/redux/es/index.js 1.08 kB {0} [built]
 [277] ./client/store.ts 1.95 kB {1} [built]
 [649] ./~/react-hot-loader/patch.js 41 bytes {0} [built]
 [650] ./client/index.tsx 2.48 kB {1} [built]
 [916] ./client/styles/flags/flags16.css 41 bytes {1} [built]
 [918] ./client/styles/antd.default.less 41 bytes {1} [built]
 [919] ./client/styles/blaze.default.less 41 bytes {1} [built]
[1578] ./~/react-hot-loader/lib/patch.js 209 bytes {0} [built]
[1585] ./client/app.tsx 2.09 kB {1} [built]
[1716] ./client/rxjs-imports.tsx 1.03 kB {1} [built]
[1866] ./~/rxjs/add/operator/debounceTime.js 241 bytes {0} [built]
[1911] multi react-hot-loader/patch ./client/index.tsx 40 bytes {1} [built]
    + 1897 hidden modules
```

I also checked some other real world project benchmarks with configs implementing mentioned solutions which unfortunately indicated no real benefit for incremental hot-reload rebuild speed.
If you have some benchmark link proving that it's not the case and I can cut times below 100ms, I would be happy to check them out :)

For me the most important thing was setting `transpileOnly` flag in `ts-loader`, and have all node_modules extracted in CommonsChunkPlugin vendor bundle, so basically only my own modules are recompiled and I don't know if you can do much more for any significant boost in hot-reload incremental build speed.
Maybe you could squeeze some milliseconds but is it worth the time invested in wresting with a webpack? I'm not that sure ;) 

Some other comments:
> fork-ts-checker-webpack-plugin — With this plugin in play ts-loader only performs transpilation. ts-loader is doing less so the build is faster.
- Is it not the same with `transpileOnly` flag in `ts-loader` config? what's other benefit? (PS: I'm not using webpack to report compile-time errors, vs-code and tsc is all I ever need)

**Comment by johnnyreilly** [comment]
> Is it not the same with `transpileOnly` flag in `ts-loader` config? what's other benefit? (PS: I'm not using webpack to report compile-time errors, vs-code and tsc is all I ever need)

Ha! That's really interesting.  Essentially your aims for your build setup are different to mine.  (Which is fine by the way 😉)  You don't rely on the webpack setup to report errors and use vs-code (how does `tsc` fit in?)  I go the other way and insist upon my build setup reporting errors.  So I would only ever advocate using `transpileOnly` if you are using something else to track compile-time errors - and that's what `fork-ts-checker-webpack-plugin` gives me.

With your setup don't you run the risk of errors slipping through?  Do you catch everything in vs code? 

Again interestingly I'm not a massive fan of hot module reloading.  I'll use it if it's in a project but I'd never add it in by choice. I even wrote this: https://blog.johnnyreilly.com/2015/12/live-reload-considered-harmful.html  (Again - this is all preference!)

I guess my third diversion from your setup is that I'm not really a fan of the webpack dashboard.    I really like running with vs code as my editor, by build process running in watch mode in the vs code terminal and clicking on errors that appear in there to take me directly to errors in a project.  I find it a really productive workflow.  Once more: choices... I also like to use notifiers like https://www.npmjs.com/package/webpack-notifier so I get shouted at when I break something.

So actually, given my own aims and yours are different then probably you'd get nothing from using fork-ts-check-webpack-plugin.  But let's still be friends 🌻 ❤️ 😉 

All that said, tomorrow I'm planning to take this project and swap it over to fit my own preferences and see if that gives me a nice seed for a project I've got kicking off soon.  So thanks in advance!  And stick with choices that make you happy and productive 😎

**Comment by piotrwitek** [comment]
Thanks for sharing your experience and perspective it's really valuable insight :)

I'll try to answer some of your questions:
> You don't rely on the webpack setup to report errors and use vs-code (how does tsc fit in?)

I'm simply using tsc in watch mode in vs-code terminal, so it's basically the same idea as fork-ts-check-plugin (separate process for type-checking) but without adding complexity to my webpack config :)

> With your setup don't you run the risk of errors slipping through? Do you catch everything in vs code?

Additionally to above we got a husky with prepush hook, to find all the sneaky check type-errors before pushing local code to remote git repo :)

> Again interestingly I'm not a massive fan of hot module reloading. I'll use it if it's in a project but I'd never add it in by choice. I even wrote this: https://blog.johnnyreilly.com/2015/12/live-reload-considered-harmful.html (Again - this is all preference!)

I read your article, it seems you were mostly referring to live-reload which is a predecessor of hot-reload, but I agree with you that's it's a matter of preference.
But also I must admit that it helps me to faster iterate especially with visual changes in the UI, but it also provides great benefit with composition of different react components, for instance when you are trying to compose a new application screen or a form using your library of presentational or connected components, it's really fun and you see the changes instantly :)

> I guess my third diversion from your setup is that I'm not really a fan of the webpack dashboard. I really like running with vs code as my editor, by build process running in watch mode in the vs code terminal and clicking on errors that appear in there to take me directly to errors in a project.

It's exactly the same for me :), I don't really check webpack-dashboard during development, most of the time I check only vs-code terminal, and dashboard is running in an iterm in the background

It seems that we have more in common with our workflow that it seemed in the first place (with the exception to hot-reload of course :)

I really appreciate your positive thinking and wish you a success with an enhanced version of the boilerplate :)
If you wish I'll gladly put a link to your repo here, I could create a section to highlight similar project for people looking for something different :) 

Wish you all the best!

**Comment by johnnyreilly** [comment]
Likewise - thanks chap!
